version: "3.9"

services:
  scraper-api:
    build: .
    container_name: scraper-api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # URL base para scrapear (puedes cambiarla según tu caso)
      BASE_URL: "/outslavery"
      ABN_URL: "https://abr.business.gov.au/Search/ResultsActive"
      AU_MODERNSLAVERY: "https://modernslaveryregister.gov.au"
      # Puerto requerido por Cloud Run
      PORT: "8080"
      # Número de workers (opcional)
      UVICORN_WORKERS: "2"
      # Configuración de proxy (si tienes uno configurado)
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      # API keys loaded from .env file
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      UK_COMPANIES_ID: "https://find-and-update.company-information.service.gov.uk/search/companies"
      UK_STATEMENTS_URL: "https://modern-slavery-statement-registry.service.gov.uk"
    volumes:
      - .:/app  # Opcional: monta tu código local para desarrollo