version: "3.9"

services:
  scraper-api:
    build: .
    container_name: scraper-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      # URL base para scrapear (puedes cambiarla según tu caso)
      BASE_URL: "/outslavery"
      ABN_URL: "https://abr.business.gov.au/Search/ResultsActive"
      AU_STATEMENTS_URL: "https://modernslaveryregister.gov.au/statements/"
      # Puerto requerido por Cloud Run
      PORT: "8080"
      # Número de workers (opcional)
      UVICORN_WORKERS: "2"
      # Configuración de proxy (si tienes uno configurado)
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
    volumes:
      - .:/app  # Opcional: monta tu código local para desarrollo
